# Generated by Django 3.2.5 on 2022-12-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='GS1_company_prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
