# Generated by Django 3.2.16 on 2022-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0002_product_productionorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='production_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
