# Generated by Django 3.2.16 on 2022-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_alter_productionorder_production_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='serialnoprovider',
            field=models.CharField(default='Tracelink', max_length=60),
        ),
    ]
