# Generated by Django 3.2.5 on 2022-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_auto_20221220_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Manufacturing_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='scheduled',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
