# Generated by Django 3.2.16 on 2022-11-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0004_productionorder_serialnoprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='produced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='production_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='regulation',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='requested',
            field=models.IntegerField(default=0),
        ),
    ]
