# Generated by Django 3.2.5 on 2023-01-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0004_auto_20221221_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippo',
            name='process_no_original',
            field=models.IntegerField(null=True),
        ),
    ]
