# Generated by Django 3.2.5 on 2023-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0006_auto_20230118_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hrf1',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hrf2',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hrf3',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hrf4',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hrf5',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hrf6',
            field=models.JSONField(max_length=100, null=True),
        ),
    ]
