# Generated by Django 3.2.5 on 2023-01-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0007_auto_20230119_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracelinksettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('username', models.CharField(default=True, max_length=100)),
                ('siteid', models.IntegerField(null=True)),
                ('sftp_port', models.IntegerField(null=True)),
                ('sftp_password', models.CharField(default='password', max_length=100)),
                ('file_sender', models.CharField(default=True, max_length=100)),
                ('sending_system', models.CharField(default='system1', max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
                ('sftp_host', models.CharField(max_length=100, null=True)),
                ('sftp_username', models.CharField(default=True, max_length=100)),
                ('file_receiver', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
