# Generated by Django 3.2.5 on 2023-01-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0008_tracelinksettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracelinksettings',
            old_name='username',
            new_name='tracelink_username',
        ),
    ]
