# Generated by Django 3.2.5 on 2023-01-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0009_rename_username_tracelinksettings_tracelink_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracelinksettings',
            old_name='password',
            new_name='tracelink_password',
        ),
    ]
