# Generated by Django 3.2.5 on 2023-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0010_rename_password_tracelinksettings_tracelink_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erpsetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('erp', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_client', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_service', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_language', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_password', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_pool_size', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_server_host', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_system_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_sytem_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='erp',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_client',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_destination',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_pool_size',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_server_host',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_service',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_system_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_sytem_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sap_user',
        ),
    ]
