# Generated by Django 3.2.16 on 2022-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0011_alter_productionorder_regulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='production_date',
            field=models.DateField(null=True),
        ),
    ]
