# Generated by Django 3.2.5 on 2023-01-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0011_auto_20230124_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='ship_to_locationlookup_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='tracelink_file_sender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
