# Generated by Django 3.2.5 on 2023-01-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0012_auto_20230125_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='sgln_extension',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
