# Generated by Django 3.2.5 on 2023-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0013_locations_sgln_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finished_good_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='regulation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sscc_prn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
