# Generated by Django 3.2.5 on 2023-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0014_auto_20230127_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(default='Not Confirmed', max_length=100),
        ),
    ]
