# Generated by Django 3.2.5 on 2023-01-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0015_alter_customers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Not Confirmed', max_length=100),
        ),
    ]
