# Generated by Django 3.2.5 on 2023-01-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0017_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('markets_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
