# Generated by Django 3.2.5 on 2023-02-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0018_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='identifier',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
