# Generated by Django 3.2.5 on 2023-02-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0019_productionorder_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='AT_PZN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='BE_ABP_CODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='BR_An_visa_Registration_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='CA_DN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='CH_Swillme_dic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='CN_Subtype_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='DE_PPN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='DE_PZN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='Dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='EAN_13',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='Form_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='GR_EOF_CODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='Generic_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='HR_Croatia_National_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='IN_Product_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='IT_Bollino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='KR_KFDA_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='License_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='Manufacturing_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='NL_KLMP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='NRD_Nordic_VNR_Drug_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='PT_Aim_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='Packet_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='Revision_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='internal_material_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
