# Generated by Django 4.1.6 on 2023-02-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0020_auto_20230202_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='file_receiver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='file_sender',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='sending_system',
            field=models.CharField(default='system1', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='sftp_host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='sftp_password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='sftp_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='sftp_username',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='siteid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='tracelink_password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='tracelink_username',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
