# Generated by Django 4.1.6 on 2023-02-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0021_customers_file_receiver_customers_file_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
