# Generated by Django 4.1.6 on 2023-04-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0025_alter_product_hrf1_alter_product_hrf2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hrf1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hrf2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hrf3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hrf4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hrf5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hrf6',
        ),
    ]
