# Generated by Django 4.1.6 on 2023-04-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0026_remove_product_hrf1_remove_product_hrf2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hrf1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hrf2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hrf3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hrf4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hrf5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hrf6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
