# Generated by Django 4.1.6 on 2023-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0027_product_hrf1_product_hrf2_product_hrf3_product_hrf4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markets',
            field=models.JSONField(blank=True, default='[{"market_name":"India","checkedStatus":false}]'),
        ),
    ]
