# Generated by Django 4.1.6 on 2023-04-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0031_alter_product_markets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='markets',
        ),
    ]
