# Generated by Django 4.1.6 on 2023-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0032_remove_product_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markets',
            field=models.JSONField(blank=True, default='[{"markets_name":"India","checkedStatus":false}]'),
        ),
    ]
