# Generated by Django 4.1.6 on 2023-04-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0033_product_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippo',
            name='shipping_date',
            field=models.DateTimeField(null=True),
        ),
    ]
