# Generated by Django 4.1.6 on 2023-04-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0035_alter_shippo_shipping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
