# Generated by Django 4.1.6 on 2023-04-20 06:22

from django.db import migrations, models
import masterapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0037_alter_productionorder_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='product_Image',
            field=models.ImageField(blank=True, null=True, upload_to=masterapp.models.ProductionOrder.namefile),
        ),
    ]
