# Generated by Django 4.1.6 on 2023-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0038_alter_productionorder_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='hrf1',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='hrf2',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='hrf3',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='hrf4',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='hrf5',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='hrf6',
            field=models.JSONField(max_length=100, null=True),
        ),
    ]
