# Generated by Django 4.1.6 on 2023-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0039_productionorder_hrf1_productionorder_hrf2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='hrf1',
            field=models.JSONField(default={'null': 'null'}),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='hrf2',
            field=models.JSONField(default={'null': 'null'}),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='hrf3',
            field=models.JSONField(default={'null': 'null'}),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='hrf4',
            field=models.JSONField(default={'null': 'null'}),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='hrf5',
            field=models.JSONField(default={'null': 'null'}),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='hrf6',
            field=models.JSONField(default={'null': 'null'}),
        ),
    ]
