# Generated by Django 4.1.6 on 2023-04-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0040_alter_productionorder_hrf1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='hrf1',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='hrf2',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='hrf3',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='hrf4',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='hrf5',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='hrf6',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='hrf',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
