# Generated by Django 4.1.6 on 2023-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0041_remove_productionorder_hrf1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snprovider',
            name='extrafield',
            field=models.CharField(default='', max_length=14),
        ),
    ]
