# Generated by Django 3.2.5 on 2023-04-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0042_snprovider_extrafield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gtins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_quantity', models.PositiveIntegerField()),
                ('renewal_quantity', models.PositiveIntegerField()),
                ('last_log', models.DateTimeField(auto_now=True)),
                ('failed_attempts', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('gtin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.product')),
            ],
        ),
    ]
