# Generated by Django 4.1.6 on 2023-07-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0044_delete_erpsetting_delete_tracelinksettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
