# Generated by Django 4.1.6 on 2023-08-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0045_alter_customers_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterdataTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processordernumber', models.CharField(max_length=100, unique=True)),
                ('expiration_date', models.DateField(null=True)),
                ('lot', models.CharField(max_length=100, null=True)),
                ('gtin', models.CharField(max_length=100, null=True, unique=True)),
                ('numbers', models.JSONField(blank=True, null=True)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('hrf', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gtins',
            name='numbers',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gtins',
            name='snnumbers',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gtins',
            name='gtin',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
