# Generated by Django 4.1.6 on 2023-08-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0046_printerdatatable_gtins_numbers_gtins_snnumbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
