# Generated by Django 4.1.6 on 2023-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0047_productionorder_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloadcodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_order_number', models.CharField(max_length=20, null=True, unique=True)),
                ('serialnumberwithgtin', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
