# Generated by Django 4.1.6 on 2023-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0048_downloadcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippo',
            name='shipping_time',
            field=models.TimeField(null=True),
        ),
    ]
