# Generated by Django 4.1.6 on 2023-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0049_shippo_shipping_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
