# Generated by Django 4.1.6 on 2023-08-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0051_customers_landmark_customers_sgln_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='company_gln',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='company_prefix',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
