# Generated by Django 4.1.6 on 2023-10-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0052_alter_customers_company_gln_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
