# Generated by Django 3.2.5 on 2023-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0054_printerdatatable_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processordernumber', models.CharField(max_length=100, unique=True)),
                ('gtin', models.CharField(max_length=100, null=True, unique=True)),
                ('numbers', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('markets', models.JSONField(blank=True, default='[{"serialnumber":"grade"}]')),
            ],
        ),
    ]
