# Generated by Django 3.2.5 on 2023-11-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0055_scannertable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scannertable',
            old_name='markets',
            new_name='grade',
        ),
    ]
