# Generated by Django 3.2.5 on 2023-11-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0056_rename_markets_scannertable_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannertable',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='scannertable',
            name='processordernumber',
        ),
    ]
