# Generated by Django 3.2.5 on 2023-11-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0057_auto_20231111_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerdatatable',
            name='status',
            field=models.CharField(default='Not Print', max_length=100),
        ),
    ]
