# Generated by Django 3.2.5 on 2023-11-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0058_alter_printerdatatable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannertable',
            name='gtin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
