# Generated by Django 4.1.6 on 2023-11-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0059_scannertable_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='printed_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
