# Generated by Django 3.2.5 on 2023-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0061_alter_printerdatatable_printed_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='balanced_serialnumbers',
            field=models.JSONField(null=True),
        ),
    ]
