# Generated by Django 3.2.5 on 2023-12-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0062_printerdatatable_balanced_serialnumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='responsefield',
            field=models.BooleanField(default=False),
        ),
    ]
