# Generated by Django 4.1.6 on 2023-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0064_alter_printerdatatable_responsefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='preparebuttonresponse',
            field=models.BooleanField(null=True),
        ),
    ]
