# Generated by Django 4.1.6 on 2023-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0065_printerdatatable_preparebuttonresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='stopbtnresponse',
            field=models.BooleanField(null=True),
        ),
    ]
