# Generated by Django 4.1.6 on 2023-12-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0066_printerdatatable_stopbtnresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='start_pause_btnresponse',
            field=models.BooleanField(null=True),
        ),
    ]
