# Generated by Django 4.1.6 on 2023-12-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0067_printerdatatable_start_pause_btnresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='pause_stop_btnresponse',
            field=models.BooleanField(null=True),
        ),
    ]
