# Generated by Django 4.1.6 on 2023-12-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0069_alter_printerdatatable_pause_stop_btnresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='return_slno_btn_response',
            field=models.BooleanField(null=True),
        ),
    ]
