# Generated by Django 4.1.6 on 2023-12-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0070_printerdatatable_return_slno_btn_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannertable',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
