# Generated by Django 4.1.6 on 2024-01-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0072_reworktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='label_response',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
