# Generated by Django 4.1.6 on 2024-01-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0074_printerdatatable_child_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerdatatable',
            name='responsefield',
        ),
    ]
