# Generated by Django 4.1.6 on 2024-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0075_remove_printerdatatable_responsefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='responsefield',
            field=models.BooleanField(default=False),
        ),
    ]
