# Generated by Django 4.1.6 on 2024-02-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0076_printerdatatable_responsefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='hrf',
            field=models.JSONField(default='[{"hrf1":null,"hrf2":null,"hrf3":null,"hrf4":null,"hrf5":null,"hrf6":null,"hrf1value":null,"hrf2value":null,"hrf3value":null,"hrf4value":null,"hrf5value":null,"hrf6value":null}]', max_length=200),
        ),
    ]
