# Generated by Django 4.1.6 on 2024-02-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0081_alter_productionorder_hrf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='hrf',
        ),
    ]
