# Generated by Django 4.1.6 on 2024-02-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0083_productionorder_hrf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='hrf',
            field=models.JSONField(default='null'),
        ),
    ]
