# Generated by Django 4.1.6 on 2024-02-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0084_alter_productionorder_hrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='scannergradefield',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
