# Generated by Django 4.1.6 on 2024-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0086_remove_printerdatatable_scannergradefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='scannergradefield',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
