# Generated by Django 4.1.6 on 2024-02-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0087_printerdatatable_scannergradefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerdatatable',
            name='preparebuttonresponse',
            field=models.BooleanField(default=False),
        ),
    ]
