# Generated by Django 4.1.6 on 2024-02-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0088_alter_printerdatatable_preparebuttonresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='batchstopmessage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printerdatatable',
            name='preparebuttonresponse',
            field=models.BooleanField(null=True),
        ),
    ]
