# Generated by Django 4.1.6 on 2024-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0089_printerdatatable_batchstopmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='loadpause',
            field=models.BooleanField(default=False),
        ),
    ]
