# Generated by Django 4.1.6 on 2024-03-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0091_alter_printerdatatable_start_pause_btnresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannertable',
            name='gradevalue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scannertable',
            name='serialnumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
