# Generated by Django 4.1.6 on 2024-03-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0092_scannertable_gradevalue_scannertable_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannertable',
            name='lot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
