# Generated by Django 4.1.6 on 2024-03-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0093_scannertable_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='Rejectednumbers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
