# Generated by Django 4.1.6 on 2024-03-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0094_printerdatatable_rejectednumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyflag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerflag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='locationflag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productflag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='prodcutionorderflag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='shippo',
            name='shippoflag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
