# Generated by Django 4.1.6 on 2024-04-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0096_scannertable_finalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='acceptednumbers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
