# Generated by Django 4.1.6 on 2024-04-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0097_printerdatatable_acceptednumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_order_number', models.CharField(default='process order number', max_length=100)),
                ('batch_number', models.CharField(default='batch number', max_length=100, unique=True)),
                ('product_name', models.CharField(default='product name', max_length=100)),
                ('manufacture_loc_name', models.CharField(default='manufacture location name', max_length=100)),
                ('line_name', models.CharField(default='line name', max_length=100)),
                ('system_name', models.CharField(default='system name', max_length=100)),
                ('created_by', models.CharField(default='created by', max_length=100)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('accepted', models.IntegerField(default=0)),
                ('specimen', models.IntegerField(default=0)),
                ('damaged', models.IntegerField(default=0)),
                ('sample', models.IntegerField(default=0)),
                ('challenged', models.IntegerField(default=0)),
                ('teach', models.IntegerField(default=0)),
                ('inprocess', models.IntegerField(default=0)),
                ('rejectedbycamera', models.IntegerField(default=0)),
                ('unused', models.IntegerField(default=0)),
                ('production_date', models.DateField(null=True)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('gtin', models.CharField(max_length=100, null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('A', models.IntegerField(default=0)),
                ('B', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('D', models.IntegerField(default=0)),
                ('E', models.IntegerField(default=0)),
                ('F', models.IntegerField(default=0)),
                ('G', models.IntegerField(default=0)),
                ('H', models.IntegerField(default=0)),
                ('I', models.IntegerField(default=0)),
                ('J', models.IntegerField(default=0)),
                ('K', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('M', models.IntegerField(default=0)),
                ('N', models.IntegerField(default=0)),
                ('O', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('Q', models.IntegerField(default=0)),
                ('R', models.IntegerField(default=0)),
                ('S', models.IntegerField(default=0)),
                ('T', models.IntegerField(default=0)),
                ('U', models.IntegerField(default=0)),
                ('V', models.IntegerField(default=0)),
                ('W', models.IntegerField(default=0)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('Z', models.IntegerField(default=0)),
            ],
        ),
    ]
