# Generated by Django 4.1.6 on 2024-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0098_prodreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerdatatable',
            name='lot',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
