# Generated by Django 4.1.6 on 2024-05-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0099_alter_printerdatatable_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='available_quantity',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
    ]
