# Generated by Django 4.1.6 on 2024-05-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0100_productionorder_available_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocatednumbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=20, unique=True)),
                ('process_order_number', models.CharField(max_length=20, unique=True)),
                ('gtin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('available_quantity', models.CharField(default=False, max_length=20, null=True)),
                ('quantity', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
