# Generated by Django 4.1.6 on 2024-05-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0102_allocatednumbers_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtins',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='gtins',
            name='numbers',
        ),
        migrations.RemoveField(
            model_name='gtins',
            name='renewal_quantity',
        ),
        migrations.RemoveField(
            model_name='gtins',
            name='snnumbers',
        ),
    ]
