# Generated by Django 4.1.6 on 2024-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0103_remove_gtins_minimum_quantity_remove_gtins_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerdatatable',
            name='gtin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
