# Generated by Django 4.1.6 on 2024-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0104_alter_printerdatatable_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadcodes',
            name='batch_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
