# Generated by Django 4.1.6 on 2024-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0105_downloadcodes_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodreport',
            name='production_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='Barcodetypename',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
