# Generated by Django 4.1.6 on 2024-05-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0107_rename_a_prodreport_acceptedcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodreport',
            name='current_production_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prodreport',
            name='current_production_time',
            field=models.TimeField(null=True),
        ),
    ]
