# Generated by Django 4.1.6 on 2024-05-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0108_prodreport_current_production_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='btncontrollstatus',
            field=models.CharField(default='Not Downloaded', max_length=20),
        ),
    ]
