# Generated by Django 4.1.6 on 2024-06-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0109_productionorder_btncontrollstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerdatatable',
            name='jobstatus',
            field=models.CharField(default='Not Added', max_length=100),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='balanceflag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='shippingflag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scannertable',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='printerdatatable',
            name='preparebuttonresponse',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='printerdatatable',
            name='stopbtnresponse',
            field=models.BooleanField(default=False),
        ),
    ]
