# Generated by Django 3.2.5 on 2022-12-06 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22, unique=True)),
                ('gln_number', models.CharField(max_length=22)),
                ('address', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_taskclosed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_to_task_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(choices=[('system_pc', 'system_pc'), ('ipc', 'ipc')], max_length=20)),
                ('system_name', models.CharField(max_length=40)),
                ('line', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('manufacturinglocation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactorlocation_to_productionline', to='productionlineapp.manufacturinglocations')),
            ],
            options={
                'db_table': 'RegisteredSystem',
            },
        ),
        migrations.AddConstraint(
            model_name='registeredsystem',
            constraint=models.UniqueConstraint(fields=('manufacturinglocation_id', 'name'), name='oneproline'),
        ),
    ]
