# Generated by Django 4.1.6 on 2023-02-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionlineapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredsystem',
            old_name='id',
            new_name='Production_line_id',
        ),
    ]
