# Generated by Django 4.1.6 on 2023-02-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionlineapp', '0002_rename_id_registeredsystem_production_line_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredsystem',
            old_name='Production_line_id',
            new_name='id',
        ),
    ]
