# Generated by Django 4.1.6 on 2024-03-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionlineapp', '0003_rename_production_line_id_registeredsystem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturinglocations',
            name='manufacturingLocationflag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='registeredsystem',
            name='productionlineflag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
