# Generated by Django 4.1.6 on 2024-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionlineapp', '0004_manufacturinglocations_manufacturinglocationflag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsystem',
            name='line',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registeredsystem',
            name='system_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
