# Generated by Django 4.1.6 on 2024-05-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productionlineapp', '0005_alter_registeredsystem_line_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registeredsystem',
            name='oneproline',
        ),
        migrations.AlterField(
            model_name='registeredsystem',
            name='manufacturinglocation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactorlocation_to_productionline', to='productionlineapp.manufacturinglocations', unique=True),
        ),
        migrations.AlterModelTable(
            name='registeredsystem',
            table=None,
        ),
    ]
