# Generated by Django 3.2.16 on 2022-10-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0005_auto_20221027_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='accepted',
            field=models.CharField(default='accepted', max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='challenged',
            field=models.CharField(default='challenged', max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='damaged',
            field=models.CharField(default='damaged', max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='in_process',
            field=models.CharField(default='inprocess', max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='rejected_by_camera',
            field=models.CharField(default='rejectedbycamera', max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='sample',
            field=models.CharField(default='sample', max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='specimen',
            field=models.CharField(default='specimen', max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='teach',
            field=models.CharField(default='teach', max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='unused',
            field=models.CharField(default='unused', max_length=100),
        ),
    ]
