# Generated by Django 3.2.16 on 2022-11-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0008_auto_20221103_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='Accepted',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='Challenged',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='Damaged',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='InProcess',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='RejectedByCamera',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='Sample',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='Specimen',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='Teach',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='Unused',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
