# Generated by Django 3.2.16 on 2022-11-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0011_auto_20221118_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionreport',
            old_name='Accept',
            new_name='J',
        ),
        migrations.RenameField(
            model_name='productionreport',
            old_name='Chall',
            new_name='K',
        ),
        migrations.RenameField(
            model_name='productionreport',
            old_name='Dam',
            new_name='L',
        ),
        migrations.RenameField(
            model_name='productionreport',
            old_name='InPro',
            new_name='M',
        ),
        migrations.RenameField(
            model_name='productionreport',
            old_name='Rejected',
            new_name='N',
        ),
        migrations.RenameField(
            model_name='productionreport',
            old_name='Samp',
            new_name='O',
        ),
        migrations.RenameField(
            model_name='productionreport',
            old_name='Spec',
            new_name='P',
        ),
        migrations.RenameField(
            model_name='productionreport',
            old_name='Tea',
            new_name='Q',
        ),
        migrations.RenameField(
            model_name='productionreport',
            old_name='Unuse',
            new_name='R',
        ),
    ]
