# Generated by Django 3.2.16 on 2022-11-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0012_auto_20221118_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='S',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='T',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='U',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='V',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='W',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='X',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='Y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='Z',
            field=models.IntegerField(default=0),
        ),
    ]
