# Generated by Django 4.1.6 on 2023-02-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0014_alter_productionreport_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='Accepted',
            field=models.CharField(default='Accepted', max_length=100),
        ),
    ]
