# Generated by Django 4.1.6 on 2023-02-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0015_alter_productionreport_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreport',
            name='Accepted',
        ),
        migrations.AddField(
            model_name='productionreport',
            name='accepted',
            field=models.CharField(default='accepted', max_length=100),
        ),
    ]
