# Generated by Django 4.1.6 on 2023-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0016_remove_productionreport_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreport',
            name='Specimen',
        ),
        migrations.AddField(
            model_name='productionreport',
            name='specimen',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
