# Generated by Django 3.2.5 on 2023-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0017_remove_productionreport_specimen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreport',
            name='Challenged',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='Damaged',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='InProcess',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='RejectedByCamera',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='Sample',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='Teach',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='Unused',
        ),
        migrations.AddField(
            model_name='productionreport',
            name='challenged',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='damaged',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='inProcess',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='rejectedByCamera',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='sample',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='teach',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='unused',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='accepted',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
