# Generated by Django 4.1.6 on 2023-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0019_auto_20230221_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='production_date',
            field=models.DateField(null=True),
        ),
    ]
