# Generated by Django 4.1.6 on 2023-08-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0020_productionreport_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='challenged',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='inprocess',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='rejectedbycamera',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='sample',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='specimen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='teach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='unused',
            field=models.IntegerField(default=0),
        ),
    ]
