# Generated by Django 4.1.6 on 2024-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0021_alter_productionreport_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='gtin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='ip_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
