# Generated by Django 4.1.6 on 2023-08-04 11:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppGetTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_event', models.CharField(blank=True, max_length=100, null=True)),
                ('app_message', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('model_object_id', models.CharField(blank=True, max_length=20, null=True)),
                ('history_event', models.CharField(blank=True, max_length=100, null=True)),
                ('history_message', models.CharField(blank=True, max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('savedid', models.CharField(max_length=100)),
                ('operationdone', models.CharField(max_length=100)),
                ('donebyuser', models.CharField(max_length=100)),
                ('donebyuserrole', models.CharField(max_length=100)),
                ('donedatetime', models.DateTimeField(max_length=100)),
                ('description', models.CharField(default='True', max_length=300)),
                ('donebyemployeeid', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeid', models.CharField(default='e101', max_length=100, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('date_birth', models.DateField(null=True)),
                ('age', models.CharField(default='age', max_length=100)),
                ('place', models.CharField(default='place', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField(default='address')),
                ('mobile', models.CharField(default='phone', max_length=100)),
                ('date_join', models.DateField(null=True)),
                ('eduqu', models.CharField(default='qualification', max_length=100)),
                ('userRole', models.CharField(default='admin', max_length=100)),
                ('username', models.CharField(default='username', max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
                ('conpass', models.CharField(default='confirm password', max_length=100)),
                ('dummy1', models.CharField(default='dummy1', max_length=100)),
                ('dummy2', models.CharField(default='dummy2', max_length=100)),
                ('dummy3', models.CharField(default='dummy3', max_length=100)),
                ('dummy4', models.CharField(default='dummy4', max_length=100)),
                ('key', models.CharField(default='key', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuditHistoryOnly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelname', models.CharField(max_length=100)),
                ('operationdone', models.CharField(max_length=100)),
                ('donebyuser', models.CharField(max_length=100)),
                ('donebyuserrole', models.CharField(max_length=100)),
                ('donedatetime', models.DateTimeField(max_length=100)),
                ('datefield', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30, unique=True)),
                ('role_type', multiselectfield.db.fields.MultiSelectField(choices=[('plantserver', 'plantserver'), ('applicationserver', 'applicationserver'), ('reportserver', 'reportserver')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserrolePermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('admin', models.JSONField(default={'CREATE': 'Checked', 'DELETE': 'Checked', 'READ': 'Checked', 'UPDATE': 'Checked'})),
                ('operator', models.JSONField(default={'CREATE': 'Checked', 'DELETE': 'Checked', 'READ': 'Checked', 'UPDATE': 'Checked'})),
                ('masterdata', models.JSONField(default={'CREATE': 'Checked', 'DELETE': 'Checked', 'READ': 'Checked', 'UPDATE': 'Checked'})),
                ('supervisor', models.JSONField(default={'CREATE': 'Checked', 'DELETE': 'Checked', 'READ': 'Checked', 'UPDATE': 'Checked'})),
            ],
        ),
    ]
