# Generated by Django 4.1.6 on 2024-02-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loginmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginuname', models.CharField(max_length=100)),
            ],
        ),
    ]
