# Generated by Django 4.1.6 on 2024-03-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_loginmodel_loginuname'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='userrole',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
