# Generated by Django 4.1.6 on 2024-03-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginmodel_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='historyflag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='registerflag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
