# Generated by Django 4.1.6 on 2024-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_history_historyflag_register_registerflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loginmodel2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginuname', models.CharField(max_length=100, null=True)),
                ('userrole', models.CharField(max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='ip_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
