# Generated by Django 4.1.6 on 2024-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginmodel2_loginmodel_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='line',
            field=models.CharField(default='exit', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
