# Generated by Django 4.1.6 on 2024-06-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loginmodel_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loginmodel2',
        ),
        migrations.AddField(
            model_name='useraudithistoryonly',
            name='description',
            field=models.CharField(default='True', max_length=300),
        ),
        migrations.AddField(
            model_name='useraudithistoryonly',
            name='historyflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='historyflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
