# Generated by Django 3.2.16 on 2022-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appgettracker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
