# Generated by Django 3.2.16 on 2022-11-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20221027_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='key',
            field=models.CharField(default='key', max_length=500),
        ),
    ]
