# Generated by Django 3.2.5 on 2023-02-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapproductionorder',
            name='imn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
