# Generated by Django 3.2.16 on 2022-11-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0002_alter_sapregisteredsystem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapproductionorder',
            name='serialnoprovider',
            field=models.CharField(default='Tracelink', max_length=60),
        ),
    ]
