# Generated by Django 3.2.16 on 2022-11-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0003_sapproductionorder_serialnoprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapproductionorder',
            name='production_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
