# Generated by Django 3.2.16 on 2022-11-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0004_alter_sapproductionorder_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapproductionorder',
            name='produced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sapproductionorder',
            name='production_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sapproductionorder',
            name='regulation',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sapproductionorder',
            name='requested',
            field=models.IntegerField(default=0),
        ),
    ]
