# Generated by Django 4.1.6 on 2024-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0004_alter_sapproductionorder_imn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapproductionorder',
            name='batch_number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
