# Generated by Django 3.2.16 on 2022-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0006_auto_20221124_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapproductionorder',
            name='regulation',
            field=models.CharField(default='regulation', max_length=100),
        ),
    ]
