# Generated by Django 3.2.16 on 2022-11-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0009_alter_sapproductionorder_regulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapproductionorder',
            name='regulation',
            field=models.CharField(default='reg', max_length=100),
        ),
    ]
