# Generated by Django 3.2.16 on 2022-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0010_alter_sapproductionorder_regulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapproductionorder',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sapproductionorder',
            name='production_date',
            field=models.DateField(null=True),
        ),
    ]
