# Generated by Django 3.2.5 on 2022-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapapp', '0011_auto_20221125_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapproductionorder',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
